info:
  name: Add Inventory Stock
  type: http
  seq: 24

http:
  method: POST
  url: "{{baseUrl}}/inventory/334b0f22-bd04-4ba0-8336-d8db36923ea7/stock/add"
  headers:
    - name: Authorization
      value: Bearer {{accessToken}}
  body:
    type: json
    data: |-
      {
        "quantity": 100,
        "reason": "purchase",
        "note": "Zakup z TME"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
