info:
  name: Get All Inventories Search
  type: http
  seq: 2

http:
  method: POST
  url: "{{baseUrl}}/inventory/search"
  headers:
    - name: Authorization
      value: Bearer {{accessToken}}
  body:
    type: json
    data: |-
      {
        "name": "Tranzystor BC-385"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
