info:
  name: Update Package
  type: http
  seq: 13

http:
  method: PUT
  url: '{{baseUrl}}/inventory/packages/d2025b50-6f12-4fcf-a51d-bf6ef46184c3'
  headers:
    - name: Authorization
      value: Bearer {{accessToken}}
  body:
    type: json
    data: '{ "name": "SOT-223" }'
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
