info:
  name: Update Surface Mount
  type: http
  seq: 17

http:
  method: PUT
  url: '{{baseUrl}}/inventory/surface-mounts/5c870e8b-5692-4273-802e-df142bce8937'
  headers:
    - name: Authorization
      value: Bearer {{accessToken}}
  body:
    type: json
    data: '{ "name": "SMD" }'
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
